//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin_Page
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brand
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Brand()
        {
            this.Stores = new HashSet<Store>();
            this.StoreGroups = new HashSet<StoreGroup>();
        }
    
        public int Id { get; set; }
        public string BrandName { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool Active { get; set; }
        public string Description { get; set; }
        public string CompanyName { get; set; }
        public string ContactPerson { get; set; }
        public string PhoneNumber { get; set; }
        public string Fax { get; set; }
        public string Website { get; set; }
        public string VATCode { get; set; }
        public Nullable<int> VATTemplate { get; set; }
        public string Address { get; set; }
        public string ApiSMSKey { get; set; }
        public string SecurityApiSMSKey { get; set; }
        public Nullable<int> SMSType { get; set; }
        public string BrandNameSMS { get; set; }
        public string JsonConfigUrl { get; set; }
        public string BrandFeatureFilter { get; set; }
        public Nullable<int> WiskyId { get; set; }
        public string DefaultDashBoard { get; set; }
        public string RSAPrivateKey { get; set; }
        public string RSAPublicKey { get; set; }
        public string PGPPassword { get; set; }
        public string PGPPrivateKey { get; set; }
        public string PGPPulblicKey { get; set; }
        public string DesKey { get; set; }
        public string DesVector { get; set; }
        public string AccessToken { get; set; }
        public string TaxCode { get; set; }
        public string DefaultDomain { get; set; }
        public string DefaultImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Store> Stores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoreGroup> StoreGroups { get; set; }
    }
}
