//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin_Page
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckFace
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CheckFace()
        {
            this.Notifications = new HashSet<Notification>();
        }
    
        public int Id { get; set; }
        public Nullable<int> FaceScanMachineId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<int> Mode { get; set; }
        public bool Active { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<bool> IsUpdated { get; set; }
        public string Image { get; set; }
        public string IpWifi { get; set; }
        public string GPS { get; set; }
        public Nullable<int> WorkShiftId { get; set; }
        public string Content { get; set; }
        public Nullable<int> Statuts { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual FaceScanMachine FaceScanMachine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual WorkingShift WorkingShift { get; set; }
    }
}
