//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin_Page
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeRoleList
    {
        public int Id { get; set; }
        public int EmpId { get; set; }
        public int EmpRoleId { get; set; }
        public Nullable<System.DateTime> BeginDay { get; set; }
        public Nullable<System.DateTime> FinishDay { get; set; }
        public bool Active { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual EmployeeRole EmployeeRole { get; set; }
    }
}
