//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin_Page
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Opening { get; set; }
        public string Content { get; set; }
        public Nullable<bool> Active { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<int> CheckFaceId { get; set; }
        public string Creator { get; set; }
    
        public virtual CheckFace CheckFace { get; set; }
    }
}
