//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin_Page
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Store()
        {
            this.AttendanceDates = new HashSet<AttendanceDate>();
            this.EmployeeInStores = new HashSet<EmployeeInStore>();
            this.StoreGroupMappings = new HashSet<StoreGroupMapping>();
            this.WorkingShifts = new HashSet<WorkingShift>();
            this.FaceScanMachines = new HashSet<FaceScanMachine>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Lat { get; set; }
        public string Lon { get; set; }
        public Nullable<bool> isAvailable { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public int Type { get; set; }
        public Nullable<int> RoomRentMode { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
        public string ShortName { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<System.DateTime> OpenTime { get; set; }
        public Nullable<System.DateTime> CloseTime { get; set; }
        public string DefaultAdminPassword { get; set; }
        public Nullable<bool> HasProducts { get; set; }
        public Nullable<bool> HasNews { get; set; }
        public Nullable<bool> HasImageCollections { get; set; }
        public Nullable<bool> HasMultipleLanguage { get; set; }
        public Nullable<bool> HasWebPages { get; set; }
        public Nullable<bool> HasCustomerFeedbacks { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<bool> HasOrder { get; set; }
        public Nullable<bool> HasBlogEditCollections { get; set; }
        public string LogoUrl { get; set; }
        public string FbAccessToken { get; set; }
        public string StoreFeatureFilter { get; set; }
        public Nullable<bool> RunReport { get; set; }
        public Nullable<int> AttendanceStoreFilter { get; set; }
        public string StoreCode { get; set; }
        public Nullable<int> PosId { get; set; }
        public string StoreConfig { get; set; }
        public string DefaultDashBoard { get; set; }
        public string District { get; set; }
        public string Province { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> PaymentTypeApply { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttendanceDate> AttendanceDates { get; set; }
        public virtual Brand Brand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeInStore> EmployeeInStores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoreGroupMapping> StoreGroupMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkingShift> WorkingShifts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FaceScanMachine> FaceScanMachines { get; set; }
    }
}
