//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin_Page
{
    using System;
    using System.Collections.Generic;
    
    public partial class TokenUser
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string FcmToken { get; set; }
        public string Uid { get; set; }
        public Nullable<int> EmpId { get; set; }
        public string JwtToken { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
